-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: fix-encoding-pragma
    -   id: flake8
    -   id: check-merge-conflict
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3