version: 2
jobs:
  build:
    working_directory: ~/s4lbot
    docker:
      - image: circleci/python:3.7.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run:
          name: run tests
          command: |
            mkdir test-results
            mkdir test-reports
            pipenv run flake8 --exclude=.venv/ --ignore=E501,E402 --statistics
            pipenv run pytest --cov tests/
            pipenv run coverage xml
            pipenv run python-codacy-coverage -r coverage.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-reports
